### PR TITLE
UDP Kernel Offload

### PR DESCRIPTION
**Pull request by levaitamas**
This draft PR introduces the eBPF kernel offload for IP/UDP traffic. It is still under development, but matured enough to show  the progress, to get some feedback, and to start integrating with l7mp. 

The implementation has two main components:
[`kernel-offload/udp_kernel_offload.c`](https://github.com/l7mp/l7mp/blob/udp-kernel-offload/kernel-offload/udp_kernel_offload.c) implements the eBPF program.  
[`udp-kernel-offload.js`](https://github.com/l7mp/l7mp/blob/udp-kernel-offload/udp-kernel-offload.js) provides simple API for l7mp to manage the kernel offload.

The offload relies on the [node_bpf](https://github.com/mildsunrise/node_bpf) npm module which works well on glibc systems  thanks to its prebuilt libbpf, but requires custom build routine on musl systems such as alpine. No worries, the updated [Dockerfile](https://github.com/l7mp/l7mp/blob/udp-kernel-offload/Dockerfile) handles the build process. The used base node image is based on alpine 3.11 which has no ELF support for tc, therefore can not load eBPF programs. As a workaroung, I updated the base node image to alpine 3.12 which seems working.

**The API introduces the following structs:**
[`Flow`](https://github.com/l7mp/l7mp/blob/udp-kernel-offload/udp-kernel-offload.js#L42): represents a 5-tuple.  
[`FlowStat`](https://github.com/l7mp/l7mp/blob/udp-kernel-offload/udp-kernel-offload.js#L72): represents flow statistics (pkts,bytes,...).

**Exposed functions:**
[`initOffloadEngine()`](https://github.com/l7mp/l7mp/blob/udp-kernel-offload/udp-kernel-offload.js#L150): to load the eBPF program on all available network interfaces with `tc`, and create BPF maps.  
[`shutdownOffloadEngine()`](https://github.com/l7mp/l7mp/blob/udp-kernel-offload/udp-kernel-offload.js#L183): to disable the kernel-offload.  
[`requestOffload(inFlow, redirFlow, action, metrics=null)`](https://github.com/l7mp/l7mp/blob/udp-kernel-offload/udp-kernel-offload.js#L193): depending on `action` to "create" or "remove" an offload from a 5-tuple (`inFlow`) to a given 5-tuple (`redirFlow`) and query the given metrics only (default `metrics` are packets and bytes). The eBPF program supports `inFlow` that is either fully-specified, or zeroes the source IP/port.  
[`getStat(inFlow)`](https://github.com/l7mp/l7mp/blob/udp-kernel-offload/udp-kernel-offload.js#L221): query statistics of a flow.  

---
**demo**
Below is a short snippet to demonstrate offload components with the help of iperf. In this demo scenario traffic is sent to `localhost:1234`, but proxied to `localhost:1236` via `localhost:1235`. All traffic can be traced by `sudo tcpdump -i lo -en`. The eBPF program needs to be compiled beforehand (eg., `cd kernel-offload && make`).

```js
"use strict";

const child_process = require("child_process");
const uko = require("./udp-kernel-offload.js");

// define a fully-specified flow to match incoming traffic
var inFlow = new uko.Flow(0x7f000001, 5000, 0x7f000001, 1234, 17);

// define redirected flow; it needs to be fully-specified, 
// since the offload engine uses this info to rewrite the packet
var redirFlow = new uko.Flow(0x7f000001, 1235, 0x7f000001, 1236, 17);

// start the offload engine (init BPF maps, load BPF programs)
uko.initOffloadEngine();

// register an offload for this flow
uko.requestOffload(inFlow, redirFlow, "create");

// query flow statistics; should be 0 pkts, 0 bytes
var stats = uko.getStat(inFlow);
console.log(stats);

// run iperf
const iperf_str = "iperf -u -c 127.0.0.1 -p 1234 -B 127.0.0.1:5000 -l 100 -t 2";
console.log(iperf_str);
const iperf_cmd = child_process.execSync(iperf_str, { encoding: "utf-8" });
console.log(iperf_cmd);

// query flow statistics; should be on pair with iperf results
var stats = uko.getStat(inFlow);
console.log(stats);

// finally, shutdown the offload engine (unload BPF program, unlink BPF maps)
uko.shutdownOffloadEngine();
```
---
**TODOs:**  
- [x]  ~~Do not use globally pinned eBPF maps, since it can cause trouble when multiple l7mp instances run on the same kernel.~~
- [x]  Integrate UDP kernel offload with l7mp.

Comments, commits, etc. are welcome.

### CODE REVIEW

**Comment by nemethf** [comment]
I let others make a detailed review, but please add copyright blurbs to the new source files. Thanks.

**Comment by rg0now** [comment]
Thanks, this is really amazing work, long-awaited feature. Apart from the copyright blurb, can you please also fix the CI build failure? Seems like it has something to do with the bpf npm module, not sure though what...

**Comment by levaitamas** [comment]
Thanks @rg0now! I rebased the PR to current master, and cherry-picked your commits.

**Review by rg0now — APPROVED** [review]

**Comment by rg0now** [comment]
Integration done, merging this despite coverage decrease

**Pull request merged**
